name: Status check on supported outlets

on:
  push:
    branches: [ workflow-fix ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 12 * * *'

jobs:
  install-xword-dl-and-test-existing-outlets:
    name: Install xword-dl and test existing outlets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.11'
      - name: Install xword-dl
        id: install
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Test New York Times rebus
        if: '!cancelled()'
        env:
          NYT_S_VALUE: ${{ secrets.NYT_S_VALUE }}
        run: |
          xword-dl nyt --settings '{"NYT-S": "'$NYT_S_VALUE'"}' -d "aug 10, 2023"
